const fs = require('fs');

const en = {
    "appTitle": "Company All Task Management",
    "login": "Login",
    "employeeId": "Employee ID",
    "mobileNumber": "Mobile Number",
    "password": "Password",
    "selectRole": "Select Role",
    "welcome": "Welcome",
    "dashboard": "Dashboard",
    "overview": "Overview",
    "aopAnalysis": "AOP Analysis",
    "totalUsers": "Total Users",
    "totalDepartments": "Total Departments",
    "activeUsers": "Active Users",
    "manageRoles": "Manage Roles",
    "setup": "Setup",
    "manageChecklists": "Manage Checklists",
    "tasks": "Tasks",
    "category": "Category",
    "type": "Type",
    "target": "Target",
    "achieved": "Achieved",
    "shortfall": "Shortfall",
    "noAopData": "No AOP Data available",
    "myMis": "My MIS",
    "workerMis": "Worker MIS",
    "qcReports": "QC Reports",
    "workLogs": "Work Logs",
    "ratings": "Ratings",
    "home": "Home",
    "logout": "Logout"
};

const hi = {
    "appTitle": "कंपनी ऑल टास्क मैनेजमेंट",
    "login": "लॉग इन करें",
    "employeeId": "कर्मचारी आईडी",
    "mobileNumber": "मोबाइल नंबर",
    "password": "पासवर्ड",
    "selectRole": "भूमिका चुनें",
    "welcome": "स्वागत है",
    "dashboard": "डैशबोर्ड",
    "overview": "अवलोकन",
    "aopAnalysis": "एओपी विश्लेषण",
    "totalUsers": "कुल उपयोगकर्ता",
    "totalDepartments": "कुल विभाग",
    "activeUsers": "सक्रिय उपयोगकर्ता",
    "manageRoles": "भूमिकाएं प्रबंधित करें",
    "setup": "सेटअप",
    "manageChecklists": "चेकलिस्ट प्रबंधित करें",
    "tasks": "कार्य",
    "category": "श्रेणी",
    "type": "प्रकार",
    "target": "लक्ष्य",
    "achieved": "प्राप्त",
    "shortfall": "कमी",
    "noAopData": "कोई एओपी डेटा उपलब्ध नहीं है",
    "myMis": "मेरा एमआईएस",
    "workerMis": "कार्यकर्ता एमआईएस",
    "qcReports": "क्यूसी रिपोर्ट",
    "workLogs": "कार्य लॉग",
    "ratings": "रेटिंग",
    "home": "होम",
    "logout": "लॉग आउट"
};

const mr = {
    "appTitle": "कंपनी ऑल टास्क मॅनेजमेंट",
    "login": "लॉग इन करा",
    "employeeId": "कर्मचारी आयडी",
    "mobileNumber": "मोबाईल नंबर",
    "password": "पासवर्ड",
    "selectRole": "भूमिका निवडा",
    "welcome": "स्वागत आहे",
    "dashboard": "डॅशबोर्ड",
    "overview": "विहंगावलोकन",
    "aopAnalysis": "एओपी विश्लेषण",
    "totalUsers": "एकूण वापरकर्ते",
    "totalDepartments": "एकूण विभाग",
    "activeUsers": "सक्रिय वापरकर्ते",
    "manageRoles": "भूमिका व्यवस्थापित करा",
    "setup": "सेटअप",
    "manageChecklists": "चेकलिस्ट व्यवस्थापित करा",
    "tasks": "कार्य",
    "category": "श्रेणी",
    "type": "प्रकार",
    "target": "लक्ष्य",
    "achieved": "प्राप्त",
    "shortfall": "कमतरता",
    "noAopData": "कोणताही एओपी डेटा उपलब्ध नाही",
    "myMis": "माझे एमआयएस",
    "workerMis": "कामगार एमआयएस",
    "qcReports": "क्यूसी अहवाल",
    "workLogs": "वर्क लॉग",
    "ratings": "रेटिंग",
    "home": "होम",
    "logout": "लॉग आउट"
};

fs.writeFileSync('MOBILEAPP/lib/core/l10n/app_en.arb', JSON.stringify(en, null, 4));
fs.writeFileSync('MOBILEAPP/lib/core/l10n/app_hi.arb', JSON.stringify(hi, null, 4));
fs.writeFileSync('MOBILEAPP/lib/core/l10n/app_mr.arb', JSON.stringify(mr, null, 4));
